# Use node version 16 image to build the react app
FROM node:21.5-alpine3.18 as builder
# Set the working directory
WORKDIR /app
# Copy package.json and yarn.lock files
COPY package.json yarn.lock ./
# Install dependencies
RUN yarn install --frozen-lockfile
# Copy the rest of the files
COPY . .
# Build the project
RUN yarn build
# Use nginx version stable-alpine image to serve the react app
FROM nginx:stable-alpine
# Copy the build folder from the react app to the nginx html folder
COPY --from=builder /app/build /usr/share/nginx/html
# Expose port 80
EXPOSE 3000
# Start nginx when the container has provisioned.
CMD ["nginx", "-g", "daemon off;"]
