version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ./Frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
